### ISSUE TITLE
GUI screen showed up, then closed automatically while testing to run plot_label_foci.py

### ISSUE THREAD

**Issue by XinQi7788** [nipy/PySurfer#307]
=======================
Generate Surface Labels
=======================

Define a label that is centered on a specific vertex in the surface mesh. Plot
that label and the focus that defines its center.

Exception occurred in traits notification handler for object: <mayavi.core.ui.mayavi_scene.MayaviScene object at 0x7f03197a1a90>, trait: disable_render, old value: True, new value: False
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/traits/trait_notifiers.py", line 342, in __call__
    self.handler(*args)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tvtk/pyface/tvtk_scene.py", line 900, in _disable_render_changed
    self.render()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tvtk/pyface/ui/qt4/scene.py", line 351, in render
    self._vtk_control.Render()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py", line 560, in Render
    self.update()
RuntimeError: wrapped C/C++ object of type _VTKRenderWindowInteractor has been deleted

**Comment by gygzhang** [comment]
hi, did you fix it?

**Comment by ruilongXIA** [comment]
Come cross the same question, hope pysurfer team solve this problem :D
https://9to5answer.com/pyqt-runtimeerror-wrapped-c-c-object-has-been-deleted
